### ISSUE TITLE
On browser close, how to wait it has really closed ?

### ISSUE THREAD

**Issue by momala454** [chrome-php/chrome#120]
I'm using a file descriptor to log errors and fclosing it after calling 
browser->close();

however, the library is trying to log event after close have been called:

Fatal error: Uncaught LogicException: The stream resource has been __destruct() too early in /headless-chromium-php/vendor/apix/log/src/Logger/Stream.php:57
Stack trace:
#0 /headless-chromium-php/vendor/apix/log/src/Logger/AbstractLogger.php(116): Apix\Log\Logger\Stream->write(Object(Apix\Log\LogEntry))
#1 /headless-chromium-php/vendor/apix/log/src/Logger/AbstractLogger.php(102): Apix\Log\Logger\AbstractLogger->process(Object(Apix\Log\LogEntry))
#2 /headless-chromium-php/vendor/psr/log/Psr/Log/AbstractLogger.php(126): Apix\Log\Logger\AbstractLogger->log('debug', 'process: killin...', Array)
#3 /headless-chromium-php/vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(172): Psr\Log\AbstractLogger->debug('process: killin...')
#4 [internal function]: HeadlessChromium\Browser\BrowserProcess->kill()
#5 {main}
  thrown in /headless-chromium-php/vendor/apix/log/src/Logger/Stream.php on line 57

Even putting a sleep after close() doesn't work, it looks like php is not closing the browser directly when i call close()

**Comment by momala454** [comment]
dirty workaround
on processAwareBrowser, change this to public :
public $browserProcess;

then call before close() : 
$browser->browserProcess->setLogger(new Apix\Log\Logger\Stream('php://stdout'));

**Comment by momala454** [comment]
don't close
